routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ClienteController;
use App\Http\Controllers\TransacaoController;



Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// Rotas protegidas por autenticação
Route::middleware(['auth'])->group(function () {
    Route::get('/vendas', [App\Http\Controllers\HomeController::class, 'index'])->name('vendas');
    Route::resource('clientes', ClienteController::class);
    Route::resource('transacao', TransacaoController::class);
});

/*
Route::prefix('clientes')->group(function () {
    Route::get('/', [ClienteController::class, 'index'])->name('clientes');
    Route::get('/{cliente}', [ClienteController::class, 'view'])->name('clientes.view');
    Route::get('/criar', [ClienteController::class, 'create'])->name('clientes.create');
    Route::get('/editar/{cliente}', [ClienteController::class, 'edit'])->name('cliente.edit');

    Route::post('/store', [ClienteController::class, 'store'])->name('clientes.store');
    Route::put('/update/{cliente}', [ClienteController::class, 'update'])->name('clientes.update');
});*/

app/Models/Cliente.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cliente extends Model {
    use HasFactory;

    protected $table = 'clientes'; // Nome da tabela
    protected $fillable = [
        'user_id',
        'nome',
        'cpf',
        'endereco',
        'descricao',
        'telefone',
        'divida_total'
    ]; // Colunas que podem ser preenchidas em massa

    // Relacionamento: Um usuário pode ter muitos pedidos
    public function transacoes() {
        return $this->hasMany(Transacao::class);
    }
}
 

app/Http/Controllers/ClienteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;
use Illuminate\Database\QueryException;

use App\Models\Cliente;
use Illuminate\Http\Request;

class ClienteController extends Controller {
    public function index() {

        return view('clientes.indexClientes', ['clientes' => Cliente::where('user_id',Auth::user()->id)->paginate(10)]);
    }

    public function create() {

        return view('clientes.createCliente');
    }

    public function show($clienteId) {

        $cliente = Cliente::find($clienteId);

        return view('clientes.showCliente', ['cliente' => $cliente]);
    }



    public function store(Request $request) {
        // Validação dos dados

        $request->validate([
            'nome' => 'required|string|max:255|unique:clientes',
            'cpf' => 'required|string|max:14|formato_cpf|unique:clientes',
            'telefone' => 'required|string|max:20',
            'endereco' => 'nullable|string|max:255',
            'descricao' => 'nullable|string',
        ], $this->massageError());

    
        // Criação do cliente
        $cliente = Cliente::create([
            'user_id' => Auth::user()->id,
            'nome' => $request->input('nome'),
            'cpf' => $request->input('cpf'),
            'telefone' => $request->input('telefone'),
            'endereco' => $request->input('endereco'),
            'descricao' => $request->input('descricao'),
        ]);

        // Redireciona ou realiza outra ação, se necessário
        return redirect()->route('clientes.index');  // Substitua 'nome_da_rota' pela rota desejada

    }

    public function edit($cliente) {

        $cliente = Cliente::where('nome', $cliente)->first();

        // dd($cliente);
        return view('clientes.editCliente', ['cliente' => $cliente]);
    }

    public function update(Request $request, $clienteId) {
        // Validação dos dados
        $request->validate([
            'nome' => 'required|string|max:255|unique:clientes,nome,' . $clienteId,
            'cpf' => 'required|string|max:14|formato_cpf|unique:clientes,cpf,' . $clienteId,
            'telefone' => 'required|string|max:20',
            'endereco' => 'nullable|string|max:255',
            'descricao' => 'nullable|string',
        ], $this->massageError());

        // Atualização do cliente
        $cliente = Cliente::findOrFail($clienteId);

        $cliente->update([
            'nome' => $request->input('nome'),
            'cpf' => $request->input('cpf'),
            'telefone' => $request->input('telefone'),
            'endereco' => $request->input('endereco'),
            'descricao' => $request->input('descricao'),
        ]);

        // Redireciona ou realiza outra ação, se necessário
        return redirect()->route('clientes.index');
    }
    public function destroy($cliente) {
        // Encontrar o cliente pelo ID no banco de dados
        $cliente = Cliente::find($cliente);

        // Verificar se o cliente foi encontrado
        if (!$cliente) {
            // Caso o cliente não seja encontrado, redirecionar ou retornar uma resposta adequada
            return redirect()->route('clientes.index')->with('error', 'Cliente não encontrado.');
        }

        // Excluir o cliente do banco de dados
        $cliente->delete();

        // Redirecionar para a lista de clientes com uma mensagem de sucesso
        return redirect()->route('clientes.index')->with('success', 'Cliente excluído com sucesso.');
    }

    public function massageError() {
        // Mensagens personalizadas
        $mensagens = [
            'nome.required' => 'O campo nome é obrigatório.',
            'nome.string' => 'O campo nome deve ser uma string.',
            'nome.max' => 'O campo nome não pode ter mais de :max caracteres.',
            'nome.unique' => 'O nome já está em uso.',

            'cpf.required' => 'O campo CPF é obrigatório.',
            'cpf.string' => 'O campo CPF deve ser uma string.',
            'cpf.max' => 'O campo CPF não pode ter mais de :max caracteres.',
            'cpf.formato_cpf' => 'O CPF informado não está em um formato válido.',
            'cpf.unique' => 'O CPF já está cadastrado.',

            'telefone.required' => 'O campo telefone é obrigatório.',
            'telefone.telefone_com_ddd' => 'O telefone não está em um formato válido.',
            'telefone.string' => 'O campo telefone deve ser uma string.',
            'telefone.max' => 'O campo telefone não pode ter mais de :max caracteres.',

            'endereco.string' => 'O campo endereço deve ser uma string.',
            'endereco.max' => 'O campo endereço não pode ter mais de :max caracteres.',

            'descricao.string' => 'O campo descrição deve ser uma string.',
        ];

        return $mensagens;
    }
}

resources/views/clientes/createCliente.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif


                    <div class="row align-items-center justify-content-between">

                        <div class="col-8">
                            <h1><i class="bi bi-person-fill-add"></i> Novo cliente</h1>
                        </div>
                        <div class="col-4 text-end">
                            <button type="submit" form="formCreateCliente"
                                class="btn btn-lg btn-success">Salvar <i class="bi bi-check-lg"></i>
                            </button>
                        </div>

                    </div>


                    <form id="formCreateCliente" method="POST" action="{{ route('clientes.store') }}">
                        @csrf

                        <div class="row gx-4 gy-2">

                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul class="mb-0">
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif

                            <div class="col-lg-7 form-group">
                                <label for="nome">Nome</label>
                                <input type="text" required class="form-control" name="nome" id="nome"
                                    placeholder="Digite seu nome">
                            </div>

                            <!-- Campo CPF -->
                            <div class="col-lg-5 form-group">
                                <label for="cpf">CPF</label>
                                <input type="text" required class="form-control" id="cpf" name="cpf"
                                    placeholder="Digite seu CPF">
                            </div>

                            <!-- Campo Telefone -->
                            <div class="col-lg-4 form-group">
                                <label for="telefone">Telefone</label>
                                <input type="tel" onkeyup="handlePhone(event)" required class="form-control"
                                    id="telefone" name="telefone" placeholder="Digite seu telefone">
                            </div>

                            <script>
                                const handlePhone = (event) => {
                                    let input = event.target
                                    input.value = phoneMask(input.value)
                                }

                                const phoneMask = (value) => {
                                    if (!value) return ""
                                    value = value.replace(/\D/g, '')
                                    value = value.replace(/(\d{2})(\d)/, "($1) $2")
                                    value = value.replace(/(\d)(\d{4})$/, "$1-$2")
                                    return value
                                }
                            </script>
                            <!-- Campo Telefone -->
                            <div class="col-lg-8 form-group">
                                <label for="endereco">Endereço</label>
                                <input type="text" class="form-control" id="endereco" name="endereco"
                                    placeholder="Digite seu endereco">
                            </div>

                            <!-- Campo Descrição -->
                            <div class="form-group">
                                <label for="descricao">Descrição</label>
                                <textarea class="form-control" id="descricao" name="descricao" rows="3" placeholder="Digite uma descrição"></textarea>
                            </div>
                        </div>

                    </form>


                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/clientes/editCliente.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div class="row align-items-center justify-content-between">

                        <div class="col">
                            <h1><i class="bi bi-person-fill-gear"></i> Editar cliente</h1>
                        </div>
                        <div class="col text-end">
                            <button type="submit" form="formCreateCliente"
                                class="btn btn-lg btn-primary">Salvar <i class="bi bi-check-lg"></i>
                            </button>
                        </div>

                    </div>


                    <form id="formCreateCliente" method="POST" action="{{ route('clientes.update', ['cliente' => $cliente->id]) }}">
                        @method('PUT')
                        @csrf

                        <div class="row gx-4 gy-2">

                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif

                            <div class="col-lg-7 form-group">
                                <label for="nome">Nome</label>
                                <input type="text" required class="form-control" value="{{ $cliente->nome }}" name="nome" id="nome"
                                    placeholder="Digite seu nome">
                            </div>

                            <!-- Campo CPF -->
                            <div class="col-lg-5 form-group">
                                <label for="cpf">CPF</label>
                                <input type="text" required class="form-control" value="{{ $cliente->cpf }}" id="cpf" name="cpf"
                                    placeholder="Digite seu CPF">
                            </div>

                            <!-- Campo Telefone -->
                            <div class="col-lg-4 form-group">
                                <label for="telefone">Telefone</label>
                                <input type="tel" onkeyup="handlePhone(event)" value="{{ $cliente->telefone }}" required class="form-control"
                                    id="telefone" name="telefone" placeholder="Digite seu telefone">
                            </div>

                            <script>
                                const handlePhone = (event) => {
                                    let input = event.target
                                    input.value = phoneMask(input.value)
                                }

                                const phoneMask = (value) => {
                                    if (!value) return ""
                                    value = value.replace(/\D/g, '')
                                    value = value.replace(/(\d{2})(\d)/, "($1) $2")
                                    value = value.replace(/(\d)(\d{4})$/, "$1-$2")
                                    return value
                                }
                            </script>
                            <!-- Campo Telefone -->
                            <div class="col-lg-8 form-group">
                                <label for="endereco">Endereço</label>
                                <input type="text" value="{{ $cliente->endereco }}" class="form-control" id="endereco" name="endereco"
                                    placeholder="Digite seu endereco">
                            </div>

                            <!-- Campo Descrição -->
                            <div class="form-group">
                                <label for="descricao">Descrição</label>
                                <textarea class="form-control" id="descricao" name="descricao" rows="3" placeholder="Digite uma descrição">
                                    {{ $cliente->descricao }}
                                </textarea>
                            </div>
                        </div>

                    </form>


                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/clientes/indexClientes.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div class="row align-items-center justify-content-between">
                        <div class="col">
                            <h1><i class="bi bi-people-fill"></i> Clientes</h1>
                        </div>
                        <div class="col text-end">
                            <a href="{{ route('clientes.create') }}" class="btn btn-lg btn-primary">
                                Novo <i class="bi bi-plus-lg"></i></a>
                        </div>
                    </div>
                   
                    @if ($clientes->isEmpty())
                        <div class="my-3 text-center opacity-75">
                            <hr class="mb-4">
                            Nenhum usuario cadastrado...
                        </div>
                    @else

                    <div class="border rounded p-3">
                        <table id="clientesTable" class="table table-hover">
                            <thead>
                                <tr class="fs-5">
                                    <th scope="col"></th>
                                    <th scope="col">Nome</th>
                                    <th scope="col">Telefone</th>
                                    <th scope="col">Endereço</th>
                                    <th scope="col"></th>

                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($clientes as $cliente)
                                    <tr id="{{ $cliente->id }}" class="align-middle">
                                        <th class="py-3 text-center ">{{ $clientes->firstItem() + $loop->index }}</th>
                                        <td class="py-3"> {{ $cliente->nome }}</td>
                                        <td class="py-3">{{ $cliente->telefone }}</td>
                                        <td class="py-3">{{ $cliente->endereco }}</td>
                                        <td class="py-3 text-end">
                                            <a href="{{ route('clientes.edit', ['cliente' => $cliente->nome]) }}" class="btn btn-info text-light">
                                                <i class="bi bi-pencil-square"></i> Editar
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                        
                    @endif

                    <div class="row">
                        {{-- $clientes->links() --}}
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/clientes/showCliente.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <x-dadosCliente :cliente="$cliente"></x-dadosCliente>
                </div>
            </div>




            <livewire:indexTransacao :cliente="$cliente"></livewire:indexTransacao>


        </div>
    </div>
@endsection